export const weatherCodes = {
    "0": "Clear sky",
    "1": "partly cloudy",
    "2": "partly cloudy",
    "3": "partly cloudy",
    "45": "Fog",
    "48": "Fog",
    "51": "Drizzle",
    "53": "Drizzle",
    "55": "Drizzle",
    "56": "Freezing Drizzle",
    "57": "Freezing Drizzle",
    "61": "Rain",
    "63": "Rain",
    "65": "Rain",
    "66": "Freezing Rain",
    "67": "Freezing Rain",
    "71": "Snow fall",
    "73": "Snow fall",
    "75": "Snow fall",
    "77": "snow grains",
    "80": "Rain showers",
    "81": "Rain showers",
    "82": "Rain showers",
    "85": "Snow showers",
    "86": "Snow showers",
    "95": "Thunderstorm",
    "96": "Thunderstorm with hail",
    "99": "Thunderstorm with hail"
};